name: PR Tests

on: 
  pull_request:
    branches: "main"

jobs:
  build:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: docs.flashbots.net
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Test Build
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
